version: '3.0'

services:
  postgres-photo:
    image: postgres:14-alpine
    container_name: photoDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=docket
      - POSTGRES_DB=pi_frame_displayable
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
    build: .
  postgres-admin-compose:
    image: dpage/pgadmin4
    container_name: photoDB-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "watisartin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-photo