version: '3.0'

services:
  postgres-photo:
    image: postgres:14-alpine
    container_name: photoDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=docket
      - POSTGRES_DB=pi_frame_displayable
    build: .
