INSERT INTO
  type(typ_contents)
VALUES
  ('movie'), ('book'), ('comic'),
  ('video'), ('art'), ('personal'),
  ('other');

INSERT INTO
  photo(pho_file_path, pho_title, pho_typ_id)
VALUES
    ('home/piframe/dev/photo-db/posters/jpg/1993-last-action-hero-poster.jpeg', 'Last Action Hero', 1),
    ('home/piframe/dev/photo-db/posters/jpg/rotld.jpeg', 'ROTLD', 1),
    ('home/piframe/dev/photo-db/posters/jpg/Burton_KingKong.jpeg', 'King Kong', 1),
    ('home/piframe/dev/photo-db/posters/jpg/darkCrystal.jpeg', 'Dark Crystal 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/godzilla.jpeg', 'Godzilla 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1982-the-dark-crystal-poster.jpeg', 'Dark Crystal 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/totoroPoster.jpeg', 'Totoro', 1),
    ('home/piframe/dev/photo-db/posters/jpg/spiritedAway.jpg', 'Spirited Away 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/tmntColors.jpg', 'TMNT', 1),
    ('home/piframe/dev/photo-db/posters/jpg/KimJungGi_Godzilla.jpg', 'Godzilla 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/escapeFromThePlanetOfTheApes.jpeg', 'Escape from Plant of the Apes', 1),
    ('home/piframe/dev/photo-db/posters/jpg/evilDead.jpeg', 'Evil Dead', 1),
    ('home/piframe/dev/photo-db/posters/jpg/2001SpaceOdd.jpg', '2001', 1),
    ('home/piframe/dev/photo-db/posters/jpg/mechaGodzilla_oliverBarrett.jpg', 'Godzilla 3', 1),
    ('home/piframe/dev/photo-db/posters/jpg/primal.jpeg', 'Primal', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1987-near-dark-poster.jpeg', 'Near Dark', 1),
    ('home/piframe/dev/photo-db/posters/jpg/theyLive_oliverBarrett.jpg', 'They Live', 1),
    ('home/piframe/dev/photo-db/posters/jpg/theThingWolf.jpeg', 'The thing 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/topHatMonkeyGoesWest.jpg', 'Top Hat Monkey Goes West', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1989-uhf-poster.jpeg', 'UHF', 1),
    ('home/piframe/dev/photo-db/posters/jpg/gremlins2.jpeg', 'Gremlins2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/gremlins.jpeg', 'Gremlins', 1),
    ('home/piframe/dev/photo-db/posters/jpg/hellBoyCat_comic.jpg', 'Hell Boy Cat', 3),
    ('home/piframe/dev/photo-db/posters/jpg/labyrinth.jpeg', 'Labyrinth', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1993-hot-shots-part-deux-poster.jpeg', 'Hot Shots 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/ackbar_art.jpeg', 'Ackbar', 5),
    ('home/piframe/dev/photo-db/posters/jpg/1991-the-rocketeer-poster.jpeg', 'Rocketeer', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1989-akira-poster.jpeg', 'Akira 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/ET_La_Boca.jpeg', 'ET', 1),
    ('home/piframe/dev/photo-db/posters/jpg/aliensDeadOrbit.jpeg', 'Aliens Dead Orbit', 3),
    ('home/piframe/dev/photo-db/posters/jpg/frozen.jpeg', 'frozen', 1),
    ('home/piframe/dev/photo-db/posters/jpg/theForeverWar.png', 'Forever war', 2),
    ('home/piframe/dev/photo-db/posters/jpg/alien1.jpg', 'Alien', 1),
    ('home/piframe/dev/photo-db/posters/jpg/robocop.jpeg', 'robocop', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1993-surf-ninjas-poster.jpeg', 'Surf Ninjas', 1),
    ('home/piframe/dev/photo-db/posters/jpg/batman.jpeg', 'Batman', 1),
    ('home/piframe/dev/photo-db/posters/jpg/hellboyShipwreck2_comic.jpg', 'Hellboy Shipwreck 2', 3),
    ('home/piframe/dev/photo-db/posters/jpg/wizOfOz.jpeg', 'Wizard of Oz', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1993-batman-mask-of-phantasm-poster.jpeg', 'Some Batman', 1),
    ('home/piframe/dev/photo-db/posters/jpg/madMaxFuryRoad.jpeg', 'Mad Max: Fury Road', 1),
    ('home/piframe/dev/photo-db/posters/jpg/spirited-away-china-poster-2.jpeg', 'Spirited Away China', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1992-the-muppet-christmas-carol-poster.jpeg', 'Muppet Christmas', 1),
    ('home/piframe/dev/photo-db/posters/jpg/MuppetTreasureIsland.jpeg', 'Muppet Treasure Island', 1),
    ('home/piframe/dev/photo-db/posters/jpg/bladeRunna.jpeg', 'Blade Runner', 1),
    ('home/piframe/dev/photo-db/posters/jpg/zodd.jpeg', 'Zodd', 3),
    ('home/piframe/dev/photo-db/posters/jpg/yodaArt.jpg', 'Yoda', 5),
    ('home/piframe/dev/photo-db/posters/jpg/1993-robin-hood-men-in-tights-poster.jpeg', 'Robin Hood', 1),
    ('home/piframe/dev/photo-db/posters/jpg/godzillaInHell.jpeg', 'Godzilla in Hell', 1),
    ('home/piframe/dev/photo-db/posters/jpg/akiraPoster.jpeg', 'Akira 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/hellboyShipwreck_comic.jpg', 'HellBoy Shipwreck', 3),
    ('home/piframe/dev/photo-db/posters/jpg/akira.jpeg', 'Akira 3', 1),
    ('home/piframe/dev/photo-db/posters/jpg/Erwin_Coraline.jpeg', 'Coraline', 1),
    ('home/piframe/dev/photo-db/posters/jpg/twinPeaksPoster.jpeg', 'Twin Peaks 1', 1),
    ('home/piframe/dev/photo-db/posters/jpg/sevenSammurai1954.jpg', '7 Sammurai', 1),
    ('home/piframe/dev/photo-db/posters/jpg/empireStrikesBack.jpeg', 'Empire Strikes back', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1993-hocus-pocus-poster.jpeg', 'Hocus Pocus', 1),
    ('home/piframe/dev/photo-db/posters/jpg/hellboyShipwreck3_comic.jpg', 'HellBoy Shipwreck 3', 3),
    ('home/piframe/dev/photo-db/posters/jpg/1990-teenage-mutant-ninja-turtles-poster.jpeg', 'TMNT 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/1993-army-of-darkness-poster.jpeg', 'Army of Darknesss', 1),
    ('home/piframe/dev/photo-db/posters/jpg/skeletonKing.jpeg', 'Skeleton King', 3),
    ('home/piframe/dev/photo-db/posters/jpg/forbiddenPlanet1956.jpg', 'Forbidden Planet', 1),
    ('home/piframe/dev/photo-db/posters/jpg/yodaMoviePoster.jpg', 'Yoda ESB', 1),
    ('home/piframe/dev/photo-db/posters/jpg/twinPeaksLaura.jpg', 'Twin Peaks 2', 1),
    ('home/piframe/dev/photo-db/posters/jpg/sbsp_graveyardShift_francavilla.jpeg', 'SBSP', 1),
    ('home/piframe/dev/photo-db/posters/jpg/iJustWannaBeMe_JasmynArnold.jpeg', 'I just wanna be me', 5),
    ('home/piframe/dev/photo-db/posters/jpg/theThing.jpg', 'The Thing', 1),
    ('home/piframe/dev/photo-db/posters/jpg/followThatBird.jpeg', 'Follow that Bird', 1);
